---
abstract: 'generate a test database for App::CPANIDX'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0.22
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-App-CPANIDX-Database
no_index:
  directory:
    - inc
    - t
provides:
  Test::App::CPANIDX::Database:
    file: lib/Test/App/CPANIDX/Database.pm
    version: 0.02
requires:
  App::CPANIDX::Tables: 0.06
  DBD::SQLite: 1.29
  DBI: 1.609
  perl: 5.8.0
resources:
  homepage: http://github.com/bingos/test-app-cpanidx-database/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/test-app-cpanidx-database.git
version: 0.02
